from enum import Enum


class ResetOption(int, Enum):
    DELETE_OPERATIONAL_PROFILES = 0
    DELETE_FIELD_LOADED_TEST_PROFILES = 1
    RESET_DEFAULT_SMDP_ADDRESS = 2
    DELETE_PRE_LOADED_TEST_PROFILES = 3  # RSP > v3.0.0
    DELETE_PROVISIONING_PROFILES = 4  # RSP > v3.0.0
