default:
  image: python:3.13

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

before_script:
  - pip install poetry
  - pip install poetry-plugin-shell
  - poetry install --all-groups
  - poetry shell

stages:
  - linting
  - test
  - build

ruff:
  stage: linting
  image: registry.gitlab.com/pipeline-components/ruff:latest
  script:
    - ruff check --output-format=gitlab .

pytest:
  stage: test
  needs:
    - ruff
  script:
    - pytest --cov --cov-report term --cov-report xml:coverage.xml --junitxml=report.xml --cov-config=.coveragerc
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    paths:
      - report.xml
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

build:
  stage: build
  needs:
    - ruff
    - pytest
  script:
    - poetry build
