[project]
name = "resimulate"
version = "0.1.0"
description = "ReSIMulate is a terminal application built for eSIM and SIM-specific APDU analysis. It captures APDU commands, saves them, and replays them to facilitate differential testing, ensuring accurate validation and debugging of SIM interactions."
authors = [
    { name = "Niklas Bittner", email = "niklas.bittner@stud.tu-darmstadt.de" },
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "rich (>=13.9.4,<14.0.0)",
    "pyshark (>=0.6,<0.7)",
    "argcomplete (>=3.5.3,<4.0.0)",
    "rich-argparse (>=1.6.0,<2.0.0)",
    "pysim @ file:///home/niklas/Documents/documents/uni/master_thesis/pysim",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
ruff = "^0.9.4"
pre-commit = "^4.1.0"
pyright = "^1.1.394"
pytest = "^8.3.4"

[tool.poetry.dependencies]
pysim = { develop = true }
