from resimulate.fuzzing.apdu_fuzzing.euicc_info import EuiccInfoScenario
from resimulate.fuzzing.apdu_fuzzing.euicc_memory_reset import EuiccMemoryResetScenario
from resimulate.fuzzing.apdu_fuzzing.profile_download import ProfileDownloadScenario

SCENARIOS = [EuiccInfoScenario, EuiccMemoryResetScenario, ProfileDownloadScenario]
