from osmocom.construct import Bytes, GreedyBytes, HexAdapter, Utf8Adapter
from osmocom.tlv import BER_TLV_IE

from resimulate.euicc.es.models.common import TransactionId


class EuiccChallenge(BER_TLV_IE, tag=0x81):
    _construct = HexAdapter(Bytes(16))


class ServerAddress(BER_TLV_IE, tag=0x83):
    _construct = Utf8Adapter(GreedyBytes)


class ServerChallenge(BER_TLV_IE, tag=0x84):
    _construct = HexAdapter(Bytes(16))


class ServerSigned1(
    BER_TLV_IE,
    tag=0x30,
    nested=[TransactionId, EuiccChallenge, ServerAddress, ServerChallenge],
):
    """
    SGP.22 Section 5.7.13:: AuthenticateServerRequest
    ServerSigned1 ::= SEQUENCE {
        transactionId [0] TransactionId, -- The Transaction ID generated by the RSP Server
        euiccChallenge [1] Octet16, -- The eUICC Challenge
        serverAddress [3] UTF8String, -- The RSP Server address as an FQDN
        serverChallenge [4] Octet16 -- The RSP Server Challenge
    }
    """

    pass
